"""
Gera ZIPs sintéticos com as MESMAS colunas dos datasets reais do TSE 2026 (arquivos *_BRASIL.csv
e *_RJ.csv, latin-1, ';', aspas). Para testes — nenhum dado real.

Uso: python tests/gerar_dados_sinteticos.py <pasta_destino> [v1|v2]
  v1 = 40 candidatos. v2 = nova geração: +1 candidato e o candidato 5 passa a INDEFERIDO
  (serve para testar a tabela `alteracao`). Casos cobertos: CPF repetido (pessoa_id),
  valores com vírgula e ponto, texto com ';' e aspas, fundamento de indeferimento.
  Casos especiais por índice (armadilhas do CLAUDE.md):
    7  = ausente do arquivo de histórico (histórico indisponível, NÃO estreante);
    8  = saiu da urna: DS_SITUACAO_CANDIDATO_TOT = #NULO, situação em DS_SITUACAO_JULGAMENTO;
    9  = ST_DECLARAR_BENS = N e nenhum bem;
    10 = histórico só com a linha de 2026 (nenhuma candidatura anterior);
    11 = um bem com valor zero ("0,00").
    13 = ST_QUILOMBOLA = #NULO (booleano ausente deve continuar nulo, não virar "não");
    12 = nome com acentos e cedilha ("MARIA CONCEIÇÃO ARAÚJO", urna "CONCEIÇÃO ARAÚJO"), para busca.
"""
import csv, sys, zipfile, io
from pathlib import Path
destino = Path(sys.argv[1]); destino.mkdir(parents=True, exist_ok=True)
sit = sys.argv[2] if len(sys.argv) > 2 else "v1"
H = {
"consulta_cand": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO NR_TURNO CD_ELEICAO DS_ELEICAO DT_ELEICAO TP_ABRANGENCIA SG_UF SG_UE NM_UE CD_CARGO DS_CARGO SQ_CANDIDATO NR_CANDIDATO NM_CANDIDATO NM_URNA_CANDIDATO NM_SOCIAL_CANDIDATO NR_CPF_CANDIDATO DS_EMAIL CD_SITUACAO_CANDIDATURA DS_SITUACAO_CANDIDATURA TP_AGREMIACAO NR_PARTIDO SG_PARTIDO NM_PARTIDO NR_FEDERACAO NM_FEDERACAO SG_FEDERACAO DS_COMPOSICAO_FEDERACAO SQ_COLIGACAO NM_COLIGACAO DS_COMPOSICAO_COLIGACAO SG_UF_NASCIMENTO DT_NASCIMENTO NR_TITULO_ELEITORAL_CANDIDATO CD_GENERO DS_GENERO CD_GRAU_INSTRUCAO DS_GRAU_INSTRUCAO CD_ESTADO_CIVIL DS_ESTADO_CIVIL CD_COR_RACA DS_COR_RACA CD_OCUPACAO DS_OCUPACAO CD_SIT_TOT_TURNO DS_SIT_TOT_TURNO",
"consulta_cand_complementar": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_ELEICAO SQ_CANDIDATO CD_DETALHE_SITUACAO_CAND DS_DETALHE_SITUACAO_CAND CD_NACIONALIDADE DS_NACIONALIDADE CD_MUNICIPIO_NASCIMENTO NM_MUNICIPIO_NASCIMENTO NR_IDADE_DATA_POSSE ST_QUILOMBOLA CD_ETNIA_INDIGENA DS_ETNIA_INDIGENA VR_DESPESA_MAX_CAMPANHA ST_REELEICAO ST_DECLARAR_BENS NR_PROTOCOLO_CANDIDATURA NR_PROCESSO CD_SITUACAO_CANDIDATO_PLEITO DS_SITUACAO_CANDIDATO_PLEITO CD_SITUACAO_CANDIDATO_URNA DS_SITUACAO_CANDIDATO_URNA ST_CANDIDATO_INSERIDO_URNA NM_TIPO_DESTINACAO_VOTOS CD_SITUACAO_CANDIDATO_TOT DS_SITUACAO_CANDIDATO_TOT ST_PREST_CONTAS ST_SUBSTITUIDO SQ_SUBSTITUIDO SQ_ORDEM_SUPLENCIA DT_ACEITE_CANDIDATURA CD_SITUACAO_JULGAMENTO DS_SITUACAO_JULGAMENTO CD_SITUACAO_JULGAMENTO_PLEITO DS_SITUACAO_JULGAMENTO_PLEITO CD_SITUACAO_JULGAMENTO_URNA DS_SITUACAO_JULGAMENTO_URNA CD_SITUACAO_CASSACAO DS_SITUACAO_CASSACAO CD_SITUACAO_CASSACAO_MIDIA DS_SITUACAO_CASSACAO_MIDIA CD_SITUACAO_DIPLOMA DS_SITUACAO_DIPLOMA CD_GENERO_FEFC DS_GENERO_FEFC CD_COR_RACA_FEFC DS_COR_RACA_FEFC",
"bem_candidato": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO CD_ELEICAO DS_ELEICAO DT_ELEICAO SG_UF SG_UE NM_UE SQ_CANDIDATO NR_ORDEM_BEM_CANDIDATO CD_TIPO_BEM_CANDIDATO DS_TIPO_BEM_CANDIDATO DS_BEM_CANDIDATO VR_BEM_CANDIDATO DT_ULT_ATUAL_BEM_CANDIDATO HH_ULT_ATUAL_BEM_CANDIDATO",
"rede_social_candidato": "DT_GERACAO HH_GERACAO AA_ELEICAO SG_UF CD_TIPO_ELEICAO NM_TIPO_ELEICAO CD_ELEICAO DS_ELEICAO SQ_CANDIDATO NR_ORDEM_REDE_SOCIAL DS_URL",
"historico_candidatura": "DT_GERACAO HH_GERACAO ANO_ELEICAO_ATUAL SQ_CANDIDATO_ATUAL SG_UF_ATUAL ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO NR_TURNO CD_ELEICAO DS_ELEICAO DT_ELEICAO TP_ABRANGENCIA_ELEICAO SG_UF SG_UE NM_UE CD_CARGO DS_CARGO SQ_CANDIDATO NR_CANDIDATO NM_CANDIDATO NM_URNA_CANDIDATO NR_PARTIDO SG_PARTIDO NM_PARTIDO CD_SITUACAO_CANDIDATURA DS_SITUACAO_CANDIDATURA CD_SITUACAO_JULGAMENTO DS_SITUACAO_JULGAMENTO CD_SIT_TOT_TURNO DS_SIT_TOT_TURNO",
"motivo_cassacao": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO CD_ELEICAO DS_ELEICAO SG_UF SG_UE NM_UE SQ_CANDIDATO NR_PROCESSO DS_TP_MOTIVO DS_MOTIVO",
"consulta_vagas": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO CD_ELEICAO DS_ELEICAO DT_ELEICAO DT_POSSE SG_UF SG_UE NM_UE CD_CARGO DS_CARGO QT_VAGA",
"consulta_coligacao": "DT_GERACAO HH_GERACAO ANO_ELEICAO CD_TIPO_ELEICAO NM_TIPO_ELEICAO NR_TURNO CD_ELEICAO DS_ELEICAO DT_ELEICAO SG_UF SG_UE NM_UE CD_CARGO DS_CARGO TP_AGREMIACAO NR_PARTIDO SG_PARTIDO NM_PARTIDO NR_FEDERACAO NM_FEDERACAO SG_FEDERACAO DS_COMPOSICAO_FEDERACAO SQ_COLIGACAO NM_COLIGACAO DS_COMPOSICAO_COLIGACAO CD_SITUACAO_LEGENDA DS_SITUACAO NM_TIPO_DESTINACAO_VOTOS",
}
hh = "08:31:16" if sit=="v1" else "09:10:00"
N = 40 if sit=="v1" else 41
def base(): return {"DT_GERACAO":"26/09/2026","HH_GERACAO":hh,"ANO_ELEICAO":"2026","CD_ELEICAO":"6259","DS_ELEICAO":"Eleições Gerais Estaduais 2026","DT_ELEICAO":"04/10/2026","SG_UF":"RJ","SG_UE":"RJ","NM_UE":"RIO DE JANEIRO","NR_TURNO":"1","CD_TIPO_ELEICAO":"2","NM_TIPO_ELEICAO":"ELEIÇÃO ORDINÁRIA"}
rows = {k:[] for k in H}
for i in range(N):
    sq = str(190000000000+i); b=base()
    rows["consulta_cand"].append({**b,"CD_CARGO":"7","DS_CARGO":"DEPUTADO ESTADUAL","SQ_CANDIDATO":sq,"NR_CANDIDATO":str(10000+i),"NM_CANDIDATO":"MARIA CONCEIÇÃO ARAÚJO" if i == 12 else f"FULANO {i} DA SILVA","NM_URNA_CANDIDATO":"CONCEIÇÃO ARAÚJO" if i == 12 else f"FULANO {i}","NM_SOCIAL_CANDIDATO":"#NULO","NR_CPF_CANDIDATO":"111" if i<3 else str(i),"DS_EMAIL":"NÃO DIVULGÁVEL","CD_SITUACAO_CANDIDATURA":"-3","DS_SITUACAO_CANDIDATURA":"#NE","TP_AGREMIACAO":"FEDERAÇÃO","NR_PARTIDO":"13","SG_PARTIDO":"PT","NM_PARTIDO":"PARTIDO DOS TRABALHADORES","NR_FEDERACAO":"101","NM_FEDERACAO":"FE BRASIL","SG_FEDERACAO":"13-PT/65-PC do B/43-PV","SQ_COLIGACAO":"190000001","NM_COLIGACAO":"#NULO","DS_COMPOSICAO_COLIGACAO":"PT/PCdoB/PV","SG_UF_NASCIMENTO":"RJ","DT_NASCIMENTO":"15/03/1970","NR_TITULO_ELEITORAL_CANDIDATO":"999","DS_GENERO":"FEMININO","DS_GRAU_INSTRUCAO":"SUPERIOR COMPLETO","DS_ESTADO_CIVIL":"CASADO(A)","DS_COR_RACA":"PARDA","DS_OCUPACAO":"ADVOGADO","CD_SIT_TOT_TURNO":"-1","DS_SIT_TOT_TURNO":"#NULO"})
    situ = "DEFERIDO" if not (sit=="v2" and i==5) else "INDEFERIDO"
    tot, julg, urna = (("#NULO", "RENÚNCIA", "NÃO") if i == 8 else (situ, situ, "SIM"))
    rows["consulta_cand_complementar"].append({**b,"SQ_CANDIDATO":sq,"DS_NACIONALIDADE":"BRASILEIRA NATA","NM_MUNICIPIO_NASCIMENTO":"NITERÓI","NR_IDADE_DATA_POSSE":"56","ST_QUILOMBOLA":"#NULO" if i == 13 else "N","DS_ETNIA_INDIGENA":"#NULO","VR_DESPESA_MAX_CAMPANHA":"1270629.01","ST_REELEICAO":"#NE","ST_DECLARAR_BENS":"N" if i == 9 else "S","NR_PROCESSO":f"0600{i}","ST_CANDIDATO_INSERIDO_URNA":urna,"NM_TIPO_DESTINACAO_VOTOS":"Válido","DS_SITUACAO_CANDIDATO_TOT":tot,"DS_SITUACAO_JULGAMENTO":julg,"ST_SUBSTITUIDO":"N","SQ_SUBSTITUIDO":"-1"})
    for j in range(0 if i == 9 else 2):
        v = "350000,50" if j == 0 else ("0,00" if i == 11 else "1200.00")
        rows["bem_candidato"].append({**b,"SQ_CANDIDATO":sq,"NR_ORDEM_BEM_CANDIDATO":str(j+1),"DS_TIPO_BEM_CANDIDATO":"Apartamento","DS_BEM_CANDIDATO":"APTO; \"centro\"","VR_BEM_CANDIDATO":v,"DT_ULT_ATUAL_BEM_CANDIDATO":"18/09/2026"})
    rows["rede_social_candidato"].append({**b,"AA_ELEICAO":"2026","SQ_CANDIDATO":sq,"NR_ORDEM_REDE_SOCIAL":"1","DS_URL":f"https://www.instagram.com/fulano{i}"})
    hist = [] if i == 7 else [(2026,"#NULO")] if i == 10 else [(2026,"#NULO"),(2022,"Eleito por QP"),(2018,"Suplente")]
    for ano,res in hist:
        rows["historico_candidatura"].append({**b,"ANO_ELEICAO_ATUAL":"2026","SQ_CANDIDATO_ATUAL":sq,"SG_UF_ATUAL":"RJ","ANO_ELEICAO":str(ano),"TP_ABRANGENCIA_ELEICAO":"E","CD_CARGO":"7","DS_CARGO":"Deputado Estadual","SQ_CANDIDATO":str(int(sq)-ano),"NR_CANDIDATO":"1","NM_CANDIDATO":"X","NM_URNA_CANDIDATO":"X","NR_PARTIDO":"13","SG_PARTIDO":"PT","NM_PARTIDO":"PT","DS_SITUACAO_CANDIDATURA":"Apto","DS_SITUACAO_JULGAMENTO":"Deferido","CD_SIT_TOT_TURNO":"1","DS_SIT_TOT_TURNO":res})
rows["motivo_cassacao"].append({**base(),"SQ_CANDIDATO":"190000000005","NR_PROCESSO":"-1","DS_TP_MOTIVO":"Fundamentos legais de julgamento","DS_MOTIVO":"Ausência de quitação eleitoral (Lei 9.504/97)"})
rows["consulta_vagas"].append({**base(),"DT_POSSE":"01/02/2027","CD_CARGO":"7","DS_CARGO":"Deputado Estadual","QT_VAGA":"70"})
rows["consulta_coligacao"].append({**base(),"CD_CARGO":"7","DS_CARGO":"DEPUTADO ESTADUAL","TP_AGREMIACAO":"FEDERAÇÃO","NR_PARTIDO":"13","SG_PARTIDO":"PT","NM_PARTIDO":"PT","NM_FEDERACAO":"FE BRASIL","SQ_COLIGACAO":"190000001","NM_COLIGACAO":"#NULO","DS_COMPOSICAO_COLIGACAO":"PT/PCdoB/PV","DS_SITUACAO":"DEFERIDO"})
for k,cols in H.items():
    cols=cols.split(); buf=io.StringIO()
    w=csv.writer(buf,delimiter=';',quoting=csv.QUOTE_ALL,lineterminator='\n'); w.writerow(cols)
    for r in rows[k]: w.writerow([r.get(c,"#NULO") for c in cols])
    with zipfile.ZipFile(destino / f"{k}_2026.zip","w") as z:
        z.writestr(f"{k}_2026_BRASIL.csv", buf.getvalue().encode("latin-1"))
        z.writestr(f"{k}_2026_RJ.csv", buf.getvalue().encode("latin-1"))
